### ISSUE TITLE
com.fasterxml.jackson.core.JsonParseException: Expecting start_array event but got START_OBJECT

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-jackson#5]
Caused by: com.avaje.ebean.text.json.JsonIOException: com.fasterxml.jackson.core.JsonParseException: Expecting start_array event but got START_OBJECT
 at [Source: {"good":"hello","stuff":42,"customers":[{"id":1,"name":"one","version":1},{"id":2,"name":"two","version":1}]}; line: 1, column: 42]
    at com.avaje.ebeaninternal.server.text.json.DJsonContext.toList(DJsonContext.java:144)
    at com.avaje.ebeaninternal.server.text.json.DJsonContext.toList(DJsonContext.java:117)
    at org.avaje.ebeanorm.jackson.BeanListTypeDeserializer.deserialize(BeanListTypeDeserializer.java:27)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:523)
    at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
    at com.fasterxml.jackson.databind.deser.impl.BeanPropertyMap._findDeserializeAndSet2(BeanPropertyMap.java:313)
    ... 27 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Expecting start_array event but got START_OBJECT
 at [Source: {"good":"hello","stuff":42,"customers":[{"id":1,"name":"one","version":1},{"id":2,"name":"two","version":1}]}; line: 1, column: 42]
    at com.avaje.ebeaninternal.server.text.json.DJsonContext.toList(DJsonContext.java:130)
    ... 32 more

**Comment by rbygrave** [comment]
refer to https://github.com/ebean-orm/avaje-ebeanorm/issues/295
